data:extend({
  {
    type = "int-setting",
    name = "factorio-ai-assistant-companion-port",
    setting_type = "startup",
    default_value = 34197,
    minimum_value = 1,
    maximum_value = 65535,
    order = "a",
  },
  {
    type = "bool-setting",
    name = "factorio-ai-assistant-advisor-quiet-mode",
    setting_type = "runtime-global",
    default_value = false,
    order = "b-a",
  },
  {
    type = "string-setting",
    name = "factorio-ai-assistant-advisor-muted-rules",
    setting_type = "runtime-global",
    default_value = "",
    allow_blank = true,
    order = "b-b",
  },
  {
    type = "int-setting",
    name = "factorio-ai-assistant-advisor-notification-cooldown-seconds",
    setting_type = "runtime-global",
    default_value = 300,
    minimum_value = 30,
    maximum_value = 3600,
    order = "b-c",
  },
  {
    type = "bool-setting",
    name = "factorio-ai-assistant-advisor-critical-power-bypass",
    setting_type = "runtime-global",
    default_value = true,
    order = "b-d",
  },
  {
    type = "int-setting",
    name = "factorio-ai-assistant-advisor-recovery-seconds",
    setting_type = "runtime-global",
    default_value = 30,
    minimum_value = 5,
    maximum_value = 600,
    order = "b-e",
  },
  {
    type = "int-setting",
    name = "factorio-ai-assistant-advisor-research-idle-minutes",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 120,
    order = "c-a",
  },
  {
    type = "double-setting",
    name = "factorio-ai-assistant-advisor-power-satisfaction-threshold",
    setting_type = "runtime-global",
    default_value = 0.9,
    minimum_value = 0.1,
    maximum_value = 1,
    order = "d-a",
  },
  {
    type = "double-setting",
    name = "factorio-ai-assistant-advisor-critical-power-threshold",
    setting_type = "runtime-global",
    default_value = 0.5,
    minimum_value = 0,
    maximum_value = 1,
    order = "d-b",
  },
  {
    type = "int-setting",
    name = "factorio-ai-assistant-advisor-power-low-seconds",
    setting_type = "runtime-global",
    default_value = 60,
    minimum_value = 5,
    maximum_value = 600,
    order = "d-c",
  },
  {
    type = "int-setting",
    name = "factorio-ai-assistant-advisor-lubricant-zero-minutes",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 120,
    order = "e-a",
  },
  {
    type = "int-setting",
    name = "factorio-ai-assistant-advisor-oil-imbalance-minutes",
    setting_type = "runtime-global",
    default_value = 5,
    minimum_value = 1,
    maximum_value = 120,
    order = "f-a",
  },
  {
    type = "double-setting",
    name = "factorio-ai-assistant-advisor-oil-surplus-min-per-minute",
    setting_type = "runtime-global",
    default_value = 60,
    minimum_value = 0,
    maximum_value = 1000000,
    order = "f-b",
  },
  {
    type = "double-setting",
    name = "factorio-ai-assistant-advisor-petroleum-deficit-min-per-minute",
    setting_type = "runtime-global",
    default_value = 30,
    minimum_value = 0,
    maximum_value = 1000000,
    order = "f-c",
  },
  {
    type = "int-setting",
    name = "factorio-ai-assistant-advisor-science-stable-minutes",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 120,
    order = "g-a",
  },
  {
    type = "double-setting",
    name = "factorio-ai-assistant-advisor-blue-science-min-per-minute",
    setting_type = "runtime-global",
    default_value = 15,
    minimum_value = 0,
    maximum_value = 1000000,
    order = "g-b",
  },
  {
    type = "double-setting",
    name = "factorio-ai-assistant-advisor-material-deficit-ratio",
    setting_type = "runtime-global",
    default_value = 1.1,
    minimum_value = 1,
    maximum_value = 10,
    order = "h-a",
  },
  {
    type = "double-setting",
    name = "factorio-ai-assistant-advisor-material-deficit-min-per-minute",
    setting_type = "runtime-global",
    default_value = 30,
    minimum_value = 0,
    maximum_value = 1000000,
    order = "h-b",
  },
  {
    type = "int-setting",
    name = "factorio-ai-assistant-advisor-material-deficit-minutes",
    setting_type = "runtime-global",
    default_value = 5,
    minimum_value = 1,
    maximum_value = 120,
    order = "h-c",
  },
  {
    type = "double-setting",
    name = "factorio-ai-assistant-advisor-crude-decline-ratio",
    setting_type = "runtime-global",
    default_value = 0.5,
    minimum_value = 0,
    maximum_value = 1,
    order = "i-a",
  },
  {
    type = "double-setting",
    name = "factorio-ai-assistant-advisor-crude-baseline-min-per-minute",
    setting_type = "runtime-global",
    default_value = 60,
    minimum_value = 0,
    maximum_value = 1000000,
    order = "i-b",
  },
  {
    type = "int-setting",
    name = "factorio-ai-assistant-advisor-crude-decline-minutes",
    setting_type = "runtime-global",
    default_value = 5,
    minimum_value = 1,
    maximum_value = 120,
    order = "i-c",
  },
  {
    type = "double-setting",
    name = "factorio-ai-assistant-advisor-key-material-baseline-min-per-minute",
    setting_type = "runtime-global",
    default_value = 30,
    minimum_value = 0,
    maximum_value = 1000000,
    order = "i-d",
  },
  {
    type = "int-setting",
    name = "factorio-ai-assistant-advisor-production-stop-minutes",
    setting_type = "runtime-global",
    default_value = 3,
    minimum_value = 1,
    maximum_value = 120,
    order = "i-e",
  },
})
